name: Deploy Sphinx Docs to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Cache pip dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/doc-requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install runtime dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install documentation dependencies
      run: |
        pip install -r doc-requirements.txt
        ls -la

    - name: Add source code to documentation
      run: |
        sphinx-apidoc -o doc/source Unreal_Python_5 -eEM
        echo "Listing generated .rst files:"
        ls -la doc/source

    - name: Build the documentation
      run: |
        sphinx-build -b html doc doc/_build
        echo "Listing generated HTML files:"
        ls -la doc/_build

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: doc/_build/
